import os
import sys
import subprocess
from pathlib import Path
from getpass import getpass

project_root = Path(__file__).parent.absolute()

def print_header(text):
    """Print formatted header"""
    print("\n" + "=" * 70)
    print(f"  {text}")
    print("=" * 70)

def print_step(step_num, text):
    """Print step number"""
    print(f"\n📌 Step {step_num}: {text}")
    print("-" * 70)

def check_python_version():
    """Check Python version"""
    if sys.version_info < (3, 8):
        print("❌ Python 3.8 or higher is required")
        sys.exit(1)
    print(f"✅ Python {sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}")

def create_directory_structure():
    """Create required directories"""
    dirs = [
        "frontend",
        "frontend/layouts",
        "frontend/components",
        "frontend/utils",
        "scripts",
        "model_artifacts"
    ]
    
    for dir_path in dirs:
        full_path = project_root / dir_path
        full_path.mkdir(parents=True, exist_ok=True)
        (full_path / "__init__.py").touch(exist_ok=True)
    
    print("✅ Directory structure created")

def install_dependencies():
    """Install Python dependencies"""
    print("\n📦 Installing backend dependencies...")
    subprocess.run([
        sys.executable, "-m", "pip", "install", "-q",
        "-r", str(project_root / "backend" / "requirements.txt")
    ])
    
    print("📦 Installing frontend dependencies...")
    frontend_req = project_root / "frontend" / "requirements.txt"
    if frontend_req.exists():
        subprocess.run([
            sys.executable, "-m", "pip", "install", "-q",
            "-r", str(frontend_req)
        ])
    
    print("✅ Dependencies installed")

def setup_env_file():
    """Setup environment file"""
    env_path = project_root / "backend" / ".env"
    env_template = project_root / "backend" / ".env.txt"
    
    if env_path.exists():
        print("⚠️  .env file already exists")
        response = input("Overwrite? (y/n): ").lower()
        if response != 'y':
            print("Skipping .env setup")
            return
    
    print("\n🔐 Database Configuration")
    print("Please enter your Supabase database details:")
    print("(Get these from: https://supabase.com → Your Project → Settings → Database)")
    
    supabase_url = input("\nSupabase Project URL: ").strip()
    supabase_key = input("Supabase Anon Key: ").strip()
    db_password = getpass("Database Password: ")
    
    # Extract project ID from URL
    project_id = supabase_url.replace("https://", "").replace(".supabase.co", "")
    database_url = f"postgresql://postgres:{db_password}@db.{project_id}.supabase.co:5432/postgres"
    
    # Generate secret key
    import secrets
    secret_key = secrets.token_urlsafe(32)
    
    env_content = f"""# TCDAFS Configuration
# Generated by quickstart.py

# Supabase Database
SUPABASE_URL={supabase_url}
SUPABASE_KEY={supabase_key}
DATABASE_URL={database_url}

# Mode: false = use database, true = use CSV files
USE_CSV_FALLBACK=false

# JWT Authentication
SECRET_KEY={secret_key}
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=1440

# Model Configuration
MODEL_PATH=../model_artifacts/best_model.joblib

# Data Directory (for CSV fallback)
DATA_DIR=../Data

# API Configuration
API_URL=http://localhost:8000
"""
    
    with open(env_path, 'w') as f:
        f.write(env_content)
    
    print("✅ .env file created")

def check_model_exists():
    """Check if ML model exists"""
    model_path = project_root / "model_artifacts" / "best_model.joblib"
    
    if model_path.exists():
        print("✅ ML model found")
        return True
    
    print("⚠️  ML model not found")
    response = input("Train model now? This may take a few minutes. (y/n): ").lower()
    
    if response == 'y':
        print("\n🤖 Training ML model...")
        try:
            subprocess.run([
                sys.executable,
                str(project_root / "model" / "train_model_with_refs.py")
            ], check=True)
            print("✅ Model trained successfully")
            return True
        except subprocess.CalledProcessError:
            print("❌ Model training failed")
            return False
    
    return False

def check_data_migration():
    """Check if data has been migrated to database"""
    env_path = project_root / "backend" / ".env"
    
    if not env_path.exists():
        return False
    
    with open(env_path) as f:
        env_content = f.read()
        if "USE_CSV_FALLBACK=true" in env_content:
            return False
    
    print("\n📊 Database migration required")
    response = input("Migrate CSV data to database now? (y/n): ").lower()
    
    if response == 'y':
        print("\n🔄 Migrating data to database...")
        try:
            subprocess.run([
                sys.executable,
                str(project_root / "scripts" / "migrate_csv_to_db.py")
            ], check=True)
            print("✅ Data migrated successfully")
            return True
        except subprocess.CalledProcessError:
            print("❌ Migration failed")
            return False
    
    return False

def create_admin_user():
    """Create admin user"""
    print("\n👤 Admin User Setup")
    response = input("Create admin user? (y/n): ").lower()
    
    if response == 'y':
        try:
            subprocess.run([
                sys.executable,
                str(project_root / "scripts" / "create_admin.py")
            ], check=True)
        except subprocess.CalledProcessError:
            print("⚠️  Admin user creation cancelled or failed")

def print_next_steps():
    """Print next steps"""
    print_header("✅ SETUP COMPLETE!")
    
    print("\n🚀 To start the application:\n")
    print("1. Open TWO terminal windows")
    print("\n2. Terminal 1 - Start Backend:")
    print("   cd", str(project_root))
    print("   .venv\\Scripts\\activate  # Windows")
    print("   # or: source .venv/bin/activate  # Mac/Linux")
    print("   python run_server.py")
    
    print("\n3. Terminal 2 - Start Dashboard:")
    print("   cd", str(project_root))
    print("   .venv\\Scripts\\activate  # Windows")
    print("   # or: source .venv/bin/activate  # Mac/Linux")
    print("   python run_dashboard.py")
    
    print("\n4. Open browser:")
    print("   Dashboard: http://localhost:8050")
    print("   API Docs:  http://localhost:8000/docs")
    
    print("\n📚 Documentation:")
    print("   Setup Guide: See the artifacts provided")
    print("   API Reference: http://localhost:8000/docs")
    
    print("\n💡 Troubleshooting:")
    print("   - If ports are busy, stop other processes or change ports")
    print("   - Check backend/.env for correct database credentials")
    print("   - Review logs in terminal for error messages")
    
    print("\n" + "=" * 70)

def main():
    """Main setup flow"""
    print_header("TCDAFS Quick Start Setup")
    print("This script will guide you through the setup process")
    
    try:
        print_step(1, "Checking Python version")
        check_python_version()
        
        print_step(2, "Creating directory structure")
        create_directory_structure()
        
        print_step(3, "Installing dependencies")
        install_dependencies()
        
        print_step(4, "Setting up environment variables")
        setup_env_file()
        
        print_step(5, "Checking ML model")
        check_model_exists()
        
        print_step(6, "Database migration")
        check_data_migration()
        
        print_step(7, "Creating admin user")
        create_admin_user()
        
        print_next_steps()
        
    except KeyboardInterrupt:
        print("\n\n⚠️  Setup interrupted by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Setup failed: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

if __name__ == "__main__":
    main()